### ISSUE TITLE
which help doc is right?

### ISSUE THREAD

**Issue by pc10201** [lddsb/drone-dingtalk-message#18] opened 2020-02-27 04:05 UTC
http://plugins.drone.io/lddsb/drone-dingtalk-message/

https://github.com/lddsb/drone-dingtalk-message

have a lot dfifferent

**Comment by lddsb** [comment] 2020-03-04 06:57
https://github.com/lddsb/drone-dingtalk-message is the latest version

**Comment by lddsb** [comment] 2020-03-07 04:44
Duplicate of #19

**Closed as completed by lddsb** 2020-03-07 04:44 UTC
